### ISSUE TITLE
Criar Plano de Release e Plano de Iteração

### ISSUE THREAD

**Issue by tacianosilva** [ZASOUROUNIJ/SEES#21]
Planejar datas e atividades para as iterações e o plano de release.

Um modelo do plano de release pode ser encontrado no link: [Plano de Release - Projeto APF](https://github.com/tacianosilva/apf-bsi/wiki/Plano-de-Release-e-Plano-de-Itera%C3%A7%C3%A3o)

**Comment by jorge-junio** [comment]
Página do Plano de Release e Plano de Iteração: [https://github.com/ZASOUROUNIJ/SEES/wiki/Plano-de-Release-e-Plano-de-Itera%C3%A7%C3%A3o](url)
