### ISSUE TITLE
Criar página Wiki com os papéis da equipe e a matriz de competência

### ISSUE THREAD

**Issue by tacianosilva** [ZASOUROUNIJ/SEES#7]
Criar página Wiki com tabelas com os papéis da equipe e a matriz de competência. Criei um milestone de definição apenas para colocar o resumo da equipe.

**Comment by jorge-junio** [comment]
[https://github.com/ZASOUROUNIJ/SEES/wiki/Pap%C3%A9is-da-Equipe-e-Matriz-de-Compet%C3%AAncias](url)
